import type { Metadata } from "next";
import ProtectedRoute from '@/components/auth/ProtectedRoute';
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
// import { themeScript } from "@/lib/theme-script";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function DashboardLayout({ children }: { children: React.ReactNode }) {

  return (
  <html lang="en" suppressHydrationWarning >
    {/* <head>
      <script dangerouslySetInnerHTML={{ __html: themeScript() }} />
    </head> */}
    <body>
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <ProtectedRoute>
        <div className="dashboard-layout">
          {children}
        </div>
      </ProtectedRoute>
      <Toaster />
    </ThemeProvider>

    </body>
  </html>
  );
}

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         {children}
//       </body>
//     </html>
//   );
// }
